### ISSUE TITLE
me podrías pasar los datos de usuario

### ISSUE THREAD

**Issue by luishdez87** [raulperod/Inventario-mongodb#1]
quisiera logear dentro de tu app para verla mas a fondo me interesa desarrollar algo así, saludos

**Comment by raulperod** [comment]
hola, para poder logearte necesitarías primero crear una sucursal y despues crear un usuario con esa sucursal (desde consola) checa los modelos dentro de models. Hay 3 tipos de usuarios el que tiene mas poder es el que tiene "permisos" igual a 2.

**Comment by luishdez87** [comment]
muchas gracias!

**Comment by danielnunesnoc** [comment]
> hola, para poder logearte necesitarías primero crear una sucursal y despues crear un usuario con esa sucursal (desde consola) checa los modelos dentro de models. Hay 3 tipos de usuarios el que tiene mas poder es el que tiene "permisos" igual a 2.

¿Puede mostrar un ejemplo práctico de cómo hacerlo?

**Comment by raulperod** [comment]
Desde consola con mongo poner lo siguiente:

1.  use gelishtime
2.  db.sucursales.insert({ plaza: "nombre_plaza", ciudad:"nombre_ciudad"  })
3.  let sucursal = db.sucursales.findOne({plaza:"nombre_plaza"})
4.  db.usuarios.insert({ username:"username", password:"password", sucursal: sucursal, permisos:2, nombre:"nombre", apellido:"apellido", status:true  })
